# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

NODE_MODULE_EXTRA_FILES="compat underscore modern"

inherit node-module

DESCRIPTION="A collection of Lo-Dash methods as Node.js modules generated by lodash-cli"

LICENSE="MIT"
KEYWORDS="~amd64 ~x86"

DOCS=( README.md )

pkg_postinst() {
	ewarn "This package has been discontinued in favor of lodash-4.0.0"
}
